// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DataPacks struct {
	Name      *string `json:"Name"`
	DataOwner *string `json:"DataOwner"`
}

type DestinationSections struct {
	Name         *string `json:"Name"`
	FieldLabel   *string `json:"FieldLabel"`
	VariableType *string `json:"VariableType"`
}

type Field struct {
	ID        string       `json:"ID"`
	DataPacks []*DataPacks `json:"DataPacks"`
	Lineage   *Lineage     `json:"Lineage"`
}

type InputDataPacks struct {
	Name      *string `json:"Name"`
	DataOwner *string `json:"DataOwner"`
}

type InputDestinationSections struct {
	Name         *string `json:"Name"`
	FieldLabel   *string `json:"FieldLabel"`
	VariableType *string `json:"VariableType"`
}

type InputField struct {
	ID        string          `json:"ID"`
	DataPacks *InputDataPacks `json:"DataPacks"`
	Lineage   *InputLineage   `json:"Lineage"`
}

type InputLineage struct {
	Source      *InputLineageSource        `json:"Source"`
	Treatments  []*InputLineageTreatments  `json:"Treatments"`
	Destination []*InputLineageDestination `json:"Destination"`
}

type InputLineageDestination struct {
	FieldType        *string                     `json:"FieldType"`
	EntitiesSubjects []*string                   `json:"EntitiesSubjects"`
	DomainsSubjects  []*string                   `json:"DomainsSubjects"`
	Sections         []*InputDestinationSections `json:"Sections"`
	Outputs          []*string                   `json:"Outputs"`
	Apps             []*string                   `json:"Apps"`
	Clients          []*int                      `json:"Clients"`
}

type InputLineageSource struct {
	Subject   *string `json:"Subject"`
	FieldType *string `json:"FieldType"`
	URL       *string `json:"URL"`
}

type InputLineageTreatments struct {
	StromTroopersFunction *string `json:"StromTroopersFunction"`
}

type Lineage struct {
	Source      *LineageSource        `json:"Source"`
	Treatments  []*LineageTreatments  `json:"Treatments"`
	Destination []*LineageDestination `json:"Destination"`
}

type LineageDestination struct {
	FieldType        *string                `json:"FieldType"`
	EntitiesSubjects []*string              `json:"EntitiesSubjects"`
	DomainsSubjects  []*string              `json:"DomainsSubjects"`
	Sections         []*DestinationSections `json:"Sections"`
	Outputs          []*string              `json:"Outputs"`
	Apps             []*string              `json:"Apps"`
	Clients          []*int                 `json:"Clients"`
}

type LineageSource struct {
	Subject   *string `json:"Subject"`
	FieldType *string `json:"FieldType"`
	URL       *string `json:"URL"`
}

type LineageTreatments struct {
	StromTroopersFunction *string `json:"StromTroopersFunction"`
}
